### ISSUE TITLE
error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zaxerion** [hdiiofficial/sampel-wabot#1]
sewaktu tes di codehub sukses tanpa error, pas di push ke server ada error ini, udah coba trobleshoot pake link yang tertera masih sama saja

/home/runner/botwatodram/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/runner/botwatodram/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/runner/botwatodram/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/home/runner/botwatodram/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:526:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.10.0

**Comment by hdiiofficial** [comment]
Mau dipake kah reponya
